# Lets create a single neuron first

In [6]:
import numpy as np

x = np.array([2,3])
w = np.array([0.5, 0.8])
b = 1

z = np.dot(x, w) + b

a = 1 / (1 + np.exp(-z))

print(a)

0.9878715650157257


# Layer of Neurons

## 3 neurons

In [2]:
x = np.array([2, 3])

W = np.array([
    [0.5, 0.8],
    [0.2, 0.4],
    [0.9, 0.1]
])

b = np.array([1, 1, 1])

z = np.dot(W, x) + b

a = 1 / (1 + np.exp(-z))

print(a)

[0.98787157 0.93086158 0.95689275]


# Forward Propagation

## Input → Hidden Layer → Output Layer

In [3]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

X = np.array([2,3])

W1 = np.random.randn(3,2)
b1 = np.random.randn(3)

W2 = np.random.randn(1,3)
b2 = np.random.randn(1)


z1 = np.dot(W1, X) + b1
a1 = sigmoid(z1)


z2 = np.dot(W2, a1) + b2
a2 = sigmoid(z2)

print(a2)

[0.70693539]


# Neural Network with 3 hidden layers

In [2]:
import numpy as np


def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])



input_size = 2

hidden1 = 8
hidden2 = 8
hidden3 = 8

output_size = 1



np.random.seed(42)

W1 = np.random.randn(input_size, hidden1)
b1 = np.zeros((1, hidden1))

W2 = np.random.randn(hidden1, hidden2)
b2 = np.zeros((1, hidden2))

W3 = np.random.randn(hidden2, hidden3)
b3 = np.zeros((1, hidden3))

W4 = np.random.randn(hidden3, output_size)
b4 = np.zeros((1, output_size))


learning_rate = 0.01
epochs = 10000

for epoch in range(epochs):


    # Forward Pass

    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = relu(z2)

    z3 = np.dot(a2, W3) + b3
    a3 = relu(z3)

    z4 = np.dot(a3, W4) + b4
    y_pred = sigmoid(z4)

    # Loss

    loss = np.mean((y - y_pred) ** 2)

    # Backpropagation

    d_z4 = (y_pred - y) * y_pred * (1 - y_pred) # This is Sigmoid derivative # This is Error x Sigmoid derivative

    d_W4 = np.dot(a3.T, d_z4)
    d_b4 = np.sum(d_z4, axis=0, keepdims=True)

    d_a3 = np.dot(d_z4, W4.T) # These are the layers 
    d_z3 = d_a3 * relu_derivative(z3)

    d_W3 = np.dot(a2.T, d_z3) # These are the weights
    d_b3 = np.sum(d_z3, axis=0, keepdims=True)

    d_a2 = np.dot(d_z3, W3.T)
    d_z2 = d_a2 * relu_derivative(z2)

    d_W2 = np.dot(a1.T, d_z2)
    d_b2 = np.sum(d_z2, axis=0, keepdims=True)

    d_a1 = np.dot(d_z2, W2.T)
    d_z1 = d_a1 * relu_derivative(z1)

    d_W1 = np.dot(X.T, d_z1)
    d_b1 = np.sum(d_z1, axis=0, keepdims=True)

    '''
1. Compute error at current layer

2. Compute weight gradients
   dW = input * error

3. Compute bias gradients
   db = error

4. Send error backward
   dA = error * Wᵀ

5. Apply activation derivative
   dZ = dA * activation_derivative'''

    # Update Weights

    W4 -= learning_rate * d_W4
    b4 -= learning_rate * d_b4

    W3 -= learning_rate * d_W3
    b3 -= learning_rate * d_b3

    W2 -= learning_rate * d_W2
    b2 -= learning_rate * d_b2

    W1 -= learning_rate * d_W1
    b1 -= learning_rate * d_b1

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss = {loss:.4f}")



print("\nPredictions:")
print(y_pred)

Epoch 0, Loss = 0.4297
Epoch 1000, Loss = 0.0035
Epoch 2000, Loss = 0.0011
Epoch 3000, Loss = 0.0006
Epoch 4000, Loss = 0.0004
Epoch 5000, Loss = 0.0003
Epoch 6000, Loss = 0.0002
Epoch 7000, Loss = 0.0002
Epoch 8000, Loss = 0.0001
Epoch 9000, Loss = 0.0001

Predictions:
[[0.01542522]
 [0.98874642]
 [0.99289656]
 [0.00485749]]


In [5]:
import numpy as np

# ==================================
# SIGMOID
# ==================================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)


# ==================================
# TANH
# ==================================

def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2


# ==================================
# RELU
# ==================================

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)


# ==================================
# LEAKY RELU
# ==================================

def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha*x)

def leaky_relu_derivative(x, alpha=0.01):
    return np.where(x > 0, 1, alpha)


# ==================================
# LINEAR
# ==================================

def linear(x):
    return x

def linear_derivative(x):
    return np.ones_like(x)


# ==================================
# SOFTMAX
# ==================================

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)


# Softmax Jacobian (single sample)

def softmax_derivative(s):
    return np.diagflat(s) - np.outer(s, s)


# ==================================
# MSE LOSS DERIVATIVE
# ==================================

def mse_derivative(y_true, y_pred):
    return (y_pred - y_true)


# ==================================
# BINARY CROSS ENTROPY
# ==================================

def binary_cross_entropy_derivative(y_true, y_pred):
    return ((y_pred - y_true) /
            (y_pred * (1 - y_pred)))


# ==================================
# SOFTMAX + CROSS ENTROPY
# ==================================

def softmax_crossentropy_derivative(
        y_true,
        y_pred):
    return y_pred - y_true

In [8]:
import numpy as np

In [9]:
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])



input_size = 2

hidden1 = 8
hidden2 = 8
hidden3 = 8

output_size = 1



np.random.seed(42)

W1 = np.random.randn(input_size, hidden1)
b1 = np.zeros((1, hidden1))

W2 = np.random.randn(hidden1, hidden2)
b2 = np.zeros((1, hidden2))

W3 = np.random.randn(hidden2, hidden3)
b3 = np.zeros((1, hidden3))

W4 = np.random.randn(hidden3, output_size)
b4 = np.zeros((1, output_size))


learning_rate = 0.01
epochs = 10000

In [11]:
for epoch in range(epochs):

    z1 = np.dot(X,W1) + b1
    a1 = relu(z1)

    z2 = np.dot(a1,W2) + b2
    a2 = relu(z2)

    z3 = np.dot(a2,W3) + b3
    a3 = relu(z3)

    z4 = np.dot(a3,W4) + b4
    a4 = relu(z4)

    loss = np.mean((y-y_pred) **2)


    d_z4 = (y_pred - y) * y_pred * (1 - y_pred)

    dw4 = np.dot(a3.T,d_z4)
    db4 = np.sum(d_z4,axis=0,keepdims=True)

    da3 = np.dot(d_z4,W4.T)
    d_z3 = da3 * relu_derivative(z3)

    dw3 = np.dot(a2.T,d_z3)
    db3 = np.sum(d_z3,axis=0,keepdims=True)

    da2 = np.dot(d_z3,W3.T)
    d_z2 = da2 * relu_derivative(z2)

    dw2 = np.dot(a1.T, d_z2)
    db2 = np.sum(d_z2,axis=0, keepdims=True)

    da1 = np.dot(d_z2,W2.T)
    d_z1 = da1 * relu_derivative(z1)

    dw1 = np.dot(X.T, d_z1)
    db1 = np.sum(d_z1,axis=0,keepdims=True)


    W4 -= learning_rate * dw4
    W3 -= learning_rate * dw3
    W2 -= learning_rate * dw2
    W1 -= learning_rate * dw1


print("\n predictions")
print(y_pred)    


 predictions
[[0.01542522]
 [0.98874642]
 [0.99289656]
 [0.00485749]]


In [1]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def binary_cross_entropy(y, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    return -np.mean(
        y * np.log(y_pred) +
        (1 - y) * np.log(1 - y_pred)
    )



X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])




input_size = 2

hidden1 = 8
hidden2 = 8
hidden3 = 8

output_size = 1



np.random.seed(42)

W1 = np.random.randn(input_size, hidden1) * np.sqrt(2 / input_size)
b1 = np.zeros((1, hidden1))

W2 = np.random.randn(hidden1, hidden2) * np.sqrt(2 / hidden1)
b2 = np.zeros((1, hidden2))

W3 = np.random.randn(hidden2, hidden3) * np.sqrt(2 / hidden2)
b3 = np.zeros((1, hidden3))

W4 = np.random.randn(hidden3, output_size) * np.sqrt(2 / hidden3)
b4 = np.zeros((1, output_size))


learning_rate = 0.1
epochs = 10000

m = X.shape[0]


for epoch in range(epochs):



    Z1 = X @ W1 + b1
    A1 = relu(Z1)

    Z2 = A1 @ W2 + b2
    A2 = relu(Z2)

    Z3 = A2 @ W3 + b3
    A3 = relu(Z3)

    Z4 = A3 @ W4 + b4
    Y_pred = sigmoid(Z4)



    loss = binary_cross_entropy(y, Y_pred)


    dZ4 = Y_pred - y

    dW4 = (A3.T @ dZ4) / m
    db4 = np.sum(dZ4, axis=0, keepdims=True) / m


    dA3 = dZ4 @ W4.T
    dZ3 = dA3 * relu_derivative(Z3)

    dW3 = (A2.T @ dZ3) / m
    db3 = np.sum(dZ3, axis=0, keepdims=True) / m


    dA2 = dZ3 @ W3.T
    dZ2 = dA2 * relu_derivative(Z2)

    dW2 = (A1.T @ dZ2) / m
    db2 = np.sum(dZ2, axis=0, keepdims=True) / m

    dA1 = dZ2 @ W2.T
    dZ1 = dA1 * relu_derivative(Z1)

    dW1 = (X.T @ dZ1) / m
    db1 = np.sum(dZ1, axis=0, keepdims=True) / m



    W4 -= learning_rate * dW4
    b4 -= learning_rate * db4

    W3 -= learning_rate * dW3
    b3 -= learning_rate * db3

    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    if epoch % 1000 == 0:
        print(f"Epoch {epoch:5d} | Loss = {loss:.6f}")


print("\nPredictions (Probabilities):")
print(np.round(Y_pred, 4))

print("\nBinary Predictions:")
print((Y_pred > 0.5).astype(int))

print("\nActual Labels:")
print(y)

Epoch     0 | Loss = 0.762766
Epoch  1000 | Loss = 0.001723
Epoch  2000 | Loss = 0.000618
Epoch  3000 | Loss = 0.000351
Epoch  4000 | Loss = 0.000238
Epoch  5000 | Loss = 0.000177
Epoch  6000 | Loss = 0.000139
Epoch  7000 | Loss = 0.000114
Epoch  8000 | Loss = 0.000095
Epoch  9000 | Loss = 0.000082

Predictions (Probabilities):
[[2.e-04]
 [1.e+00]
 [1.e+00]
 [0.e+00]]

Binary Predictions:
[[0]
 [1]
 [1]
 [0]]

Actual Labels:
[[0]
 [1]
 [1]
 [0]]
